name: docker

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          args: |
            git submodule update --init --recursive &&
            echo $(gha name -r -u anzerr -t sync.folder) &&
            docker build -t $(gha name -r -u anzerr -t sync.folder) -t $(gha name -r -u anzerr -t sync.folder -v latest) . &&
            docker push $(gha name -r -u anzerr -t sync.folder) &&
            docker push $(gha name -r -u anzerr -t sync.folder -v latest)
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          args: |
            echo $(gha name -u anzerr) &&
            docker build -t $(gha name -u anzerr) -t $(gha name -u anzerr -v latest) . &&
            docker push $(gha name -u anzerr) &&
            docker push $(gha name -u anzerr -v latest)